// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi8-Zh8dCLUA_FHhL2g_2hLlSHHkIqRyk',
    appId: '1:609799055187:web:3643f92775480ec4bba3a6',
    messagingSenderId: '609799055187',
    projectId: 'pharmacy-b9870',
    authDomain: 'pharmacy-b9870.firebaseapp.com',
    storageBucket: 'pharmacy-b9870.firebasestorage.app',
    measurementId: 'G-FLEEXTDZKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwgAZTDZIeUkZQlTAJZWIOW6x_cjKBh08',
    appId: '1:609799055187:android:0bfa23a7e855594dbba3a6',
    messagingSenderId: '609799055187',
    projectId: 'pharmacy-b9870',
    storageBucket: 'pharmacy-b9870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrVr_tx8RZEIbTc1mgqvAJ8pDXqIOsyLA',
    appId: '1:609799055187:ios:a3b2716b1a35dba4bba3a6',
    messagingSenderId: '609799055187',
    projectId: 'pharmacy-b9870',
    storageBucket: 'pharmacy-b9870.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrVr_tx8RZEIbTc1mgqvAJ8pDXqIOsyLA',
    appId: '1:609799055187:ios:a3b2716b1a35dba4bba3a6',
    messagingSenderId: '609799055187',
    projectId: 'pharmacy-b9870',
    storageBucket: 'pharmacy-b9870.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi8-Zh8dCLUA_FHhL2g_2hLlSHHkIqRyk',
    appId: '1:609799055187:web:34da7a8669d87e8cbba3a6',
    messagingSenderId: '609799055187',
    projectId: 'pharmacy-b9870',
    authDomain: 'pharmacy-b9870.firebaseapp.com',
    storageBucket: 'pharmacy-b9870.firebasestorage.app',
    measurementId: 'G-BVRCCJQXNY',
  );
}
